apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: flask-hello-world
    app.kubernetes.io/component: flask-hello-world
    app.kubernetes.io/instance: flask-hello-world
    app.kubernetes.io/name: flask-hello-world
    app.kubernetes.io/part-of: jupyterhub
  name: flask-hello-world
spec:
  lookupPolicy:
    local: false
