apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: serverless-flask
    app.kubernetes.io/component: serverless-flask
    app.kubernetes.io/instance: serverless-flask
    app.kubernetes.io/name: serverless-flask
    app.kubernetes.io/part-of: hello-world
  name: serverless-flask
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: serverless-flask:latest
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/JeetRH/FlaskServerless.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 5