apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: hello-world
    app.openshift.io/runtime: python
  name: serverless-flask
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: hello-world
        app.openshift.io/runtime: python
    spec:
      containerConcurrency: 0
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/honda/serverless-flask:latest
        name: user-container
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
